[project]
name = "shikiho_downloader"
version = "0.1.0"
description = "Shikiho Online scraper for selected fields"
readme = "scrape_README.md"
requires-python = ">=3.9"
dependencies = [
  "playwright>=1.44.0",
]

[tool.uv]
dev-dependencies = []
